
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-security-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/security_db
      SPRING_DATASOURCE_USERNAME: secuser
      SPRING_DATASOURCE_PASSWORD: secpassword
      # KEYCLOAK INTEGRATION SETTINGS
      KEYCLOAK_ENABLED: true
      KEYCLOAK_RESOURCE: project-million-api
      KEYCLOAK_HOST: http://keycloak:8080
      KEYCLOAK_ADMIN_REALM: master
      KEYCLOAK_CUSTOMER_REALM: customer
    depends_on:
      - db
      - keycloak

  db:
    container_name: psql-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: secuser
      POSTGRES_PASSWORD: secpassword
    ports:
      - "5434:5432"
    volumes:
      - db_postgres_data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak_db
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secpassword
    ports:
      - "8081:8080"
    command: ["start-dev"]
    depends_on:
      - keycloak-db
    volumes:
      - keycloak_data:/opt/keycloak/data

  keycloak-db:
    container_name: keycloak-psql-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

volumes:
  db_postgres_data:
  keycloak_postgres_data:
  keycloak_data: