
spring:
  application.name: security-backend-api
  threads.virtual.enabled: true

keycloak:
  enabled: true
  host: http://localhost:8081
  resource: project-million-api
  principal-attribute: preferred_username
  realm_access: realm_access
  path-prefix: /protocol/openid-connect/certs
  realms:
    admin: ${keycloak.host}/realms/master
    customer: ${keycloak.host}/realms/customer