
spring:
  application.name: security-backend-api
  threads.virtual.enabled: true

keycloak:
  enabled: ${KEYCLOAK_ENABLED}
  host: ${KEYCLOAK_HOST}
  resource: ${KEYCLOAK_RESOURCE}
  principal-attribute: preferred_username
  realm_access: realm_access
  path-prefix: /protocol/openid-connect/certs
  realms:
    admin: ${keycloak.host}/realms/${KEYCLOAK_ADMIN_REALM}
    customer: ${keycloak.host}/realms/${KEYCLOAK_CUSTOMER_REALM}